# MySQL 数据库相关配置
db:
  host: 127.0.0.1  # MySQL 机器 IP 和端口，默认 127.0.0.1:3306
  username: torchpole # MySQL 用户名(建议授权最小权限集)
  password: torchpole!@# # MySQL 用户密码
  database: torchpole # torchpole 系统所用的数据库名
  max-idle-connections: 100 # MySQL 最大空闲连接数，默认 100
  max-open-connections: 100 # MySQL 最大打开的连接数，默认 100
  max-connection-life-time: 10s # 空闲连接最大存活时间，默认 10s
  log-level: 4 # GORM log level, 1: silent, 2:error, 3:warn, 4:info

# 日志配置
log:
  disable-caller: false # 是否开启 caller，如果开启会在日志中显示调用日志所在的文件和行号
  level: debug # 指定日志级别，可选值：debug, info, warn, error, fatal
  time-format:  # 指定日志时间显示格式 2006-01-02T15:04:05.999999999Z07:00